### PR TITLE
Two new tools

### PR DESCRIPTION
**Pull request by AurelienLourot**
Hi :) Great list! 

You can't see the diff here because the CR-LF in your file are strange (I suspect you work on Windows?), so somehow git considers your file as a binary file. If you want I can also fix these CR-LF so that next time you'll see nice diffs in the pull-requests. But I'm not sure, it could as well be caused by the Chinese characters.

So what I have done here is that I have separated Add-ons and Tools, and I have created subsections for the Tools (Chrome extensions, Command-line tools and Programming libraries). I have added one command-line tool (I'm the author, I hope you'll like it, https://github.com/AurelienLourot/lsankidb) and one python library (which I use in my tool's implementation: https://github.com/patarapolw/AnkiTools).

Thanks!

### CODE REVIEW

**Comment by tianshanghong** [comment]
Hi! Thanks very much for your commits. Your tools are really nice!

I found this CR-LF problem tricky too but have no idea how to deal with it. If you like, please help me fix that problem. Thanks for that in advance. 😄

**Comment by tianshanghong** [comment]
Don't worry about any Chinese characters. I have removed them from the list.

**Comment by AurelienLourot** [comment]
The Chinese characters were indeed causing the issue. Now if I touch the file, `git diff` is treating it nicely as a text file and showing me the diff. Problem solved, thanks :)

**Comment by tianshanghong** [comment]
Thank you very much, too. 🙏

**Pull request merged**
