### PR TITLE
Logo and Github star badges.

### PR DESCRIPTION
**Pull request by AurelienLourot**
Hi :) My goal here is to have your list similar to the Anki section of https://github.com/RichardLitt/endangered-languages so that they will accept to replace their Anki section with a link to your list, which is superior IMHO. 

See the result here: https://github.com/AurelienLourot/awesome-anki/tree/temp

### CODE REVIEW

**Comment by tianshanghong** [comment]
Yeah, thanks very much!
I see these badges adorable and lovely, and I'm very willing to add them. Also, I noticed that [RichardLitt/low-resource-languages#139](https://github.com/RichardLitt/low-resource-languages/issues/139) issue. Do you recommend we add these badges or wait until [RichardLitt / low-resource-languages](https://github.com/RichardLitt/low-resource-languages) work out a new solution, if they can accept this awesome-anki list?

**Comment by AurelienLourot** [comment]
Let's keep as is for now and see how it goes :)
https://github.com/RichardLitt/low-resource-languages/pull/140

**Comment by RichardLitt** [comment]
I think your badges work fine for this list. My list is considerably larger - I stopped using them because of perf issues. I got tired of the list loading erratically when I was loading it repeatedly. This isn't a problem for your scale, at all. Keep them. :)

**Comment by tianshanghong** [comment]
Haha, I'll keep it.

**Pull request merged**
